# Multiple Operating Systems
os:
  - linux
  - osx

# Testing
script: "sudo ./tests"

# IRC notification
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
      - irc.freenode.org#hyhyhy
    template:
      - "%{message} by @%{author}: See %{build_url}"
  email:
    on_success: never
    on_failure: never