# Multiple Operating Systems
os:
  - linux
  - osx

# Configuring
before_install:
  - "export DEBIAN_FRONTEND=noninteractive"
  - sudo apt-get update -qy
  - sudo apt-get upgrade -yq ruby --fix-missing
  - sudo apt-get install -yq rubygems --fix-missing

# Testing
script: "sudo ./tests"

# IRC notification
notifications:
  irc:
    on_success: change
    on_failure: change
    channels:
      - irc.freenode.org#hyhyhy
    template:
      - "%{message} by @%{author}: See %{build_url}"
  email:
    on_success: never
    on_failure: never